# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under end_to_end_databricks/resources/*
# and end_to_end_databricks/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for end_to_end_databricks Staging

on:
  push:
    branches:
      - 'main'
    paths:
      - 'end_to_end_databricks/**'
      - '.github/workflows/end_to_end_databricks-bundle-cd-staging.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./end_to_end_databricks

env:
  DATABRICKS_HOST: https://dbc-314d456b-c68f.cloud.databricks.com
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: end_to_end_databricks-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
